### ISSUE TITLE
Gmane archive link is dead

### ISSUE THREAD

**Issue by mineo** [OfflineIMAP/offlineimap.github.io#7]
See https://lars.ingebrigtsen.no/2016/07/28/the-end-of-gmane/comment-page-1/#comment-13502. It looks like this was the only archive that could be viewed on the web without registering (I'm not sure if subscribing on alioth shows some archive link).

**Comment by ghost** [comment]
Hm. Too sad that The archive still isn't available anywhere - for reasons unknown to me I don't get any mails of the mailinglist even though I'm subscribed and get a confirmation email from mailman that my mail has been accepted.
Any ideas how to solve this problem?

**Comment by nicolas33** [comment]
The archive can be found [on debian](http://lists.alioth.debian.org/pipermail/offlineimap-project/). We have to update our website, though.

**Comment by nicolas33** [comment]
> for reasons unknown to me I don't get any mails of the mailinglist even though I'm subscribed and get a confirmation email from mailman that my mail has been accepted.

I've sent my response to you with the mailing list in copy to your first email. I've replied this way to your latest email asking if the mailing list is working, too. I think the archive will be updated today.

**Comment by mineo** [comment]
Fixed with https://github.com/OfflineIMAP/offlineimap.github.io/commit/ebea16735aa9d1d92ed8bd59fb52e52536dab91d.
